LOWERCASE = [
    "a",
    "ą",
    "b",
    "c",
    "č",
    "d",
    "e",
    "ę",
    "ė",
    "f",
    "g",
    "h",
    "i",
    "į",
    "y",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "r",
    "s",
    "š",
    "t",
    "u",
    "ų",
    "ū",
    "v",
    "z",
    "ž",
]
UPPERCASE = [
    "A",
    "Ą",
    "B",
    "C",
    "Č",
    "D",
    "E",
    "Ę",
    "Ė",
    "F",
    "G",
    "H",
    "I",
    "Į",
    "Y",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "R",
    "S",
    "Š",
    "T",
    "U",
    "Ų",
    "Ū",
    "V",
    "Z",
    "Ž",
]

encryption_inputs = [
    ("Apetitas atsiranda bevalgant.", 13),
    ("Aklas aklą netoli tenuves.", 29),
    ("Visiems dalina patarimus, sau neturi.", 23),
    ("Auksinis plaktukas ir geležines duris prakala.", 12),
    ("Lenk medį, kol jaunas.", 11),
    ("Piktos gaspadinės ir duona rūgšti.", 27),
    ("Briedis girioj, o jau iešmą drožia.", 19),
    ("Jūrą perplaukęs, klane nuskendo.", 24),
    ("Kalbos – vežimais, o naudos – už grašį.", 19),
    ("Nuliūdęs kaip žemes pardavęs.", 17),
]

decryption_inputs = [
    "Ltnflmn yjįmį ižefjąkd.",
    "Pž eputfa avbca, pž fepa aejptf.",
    "Jnjr žpšnyžr, šnjr hp žpjkžr.",
    "Šhjęjhr fdphžtrhn, ądš ptnsjhr ąknfhžtrhžl.",
    "Suęų hųęk vęocm ųšęif.",
    "Zugoah ęėgoah ag fgozogoh zgąhįoh.",
    "Ųrvgr vkąmcr, z tgč jaziką gčjfrg.",
    "Yjesūpa tfžbca zfųfbcvt, yjąpųbg zšfct.",
    "Fp bfbcyfl nvprl fpcfkv fp įnvprl.",
    "Sąųuėpę ąh sejifi gąėąžpą.",
]
